# Generated by Django 5.1.4 on 2026-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLUB',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('kod', models.CharField(blank=True, null=True)),
                ('cely_nazov_klubu', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Abbreviation', models.CharField(blank=True, null=True)),
                ('FullName', models.CharField(blank=True, null=True)),
                ('LogoURL', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ROK',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sezona', models.CharField(blank=True, null=True)),
                ('klub', models.CharField(blank=True, null=True)),
                ('id_player', models.BigIntegerField(blank=True, null=True)),
                ('hlava', models.TextField(blank=True, null=True)),
                ('prve_meno', models.CharField(blank=True, null=True)),
                ('druhe_meno', models.CharField(blank=True, null=True)),
                ('cislo_dresu', models.CharField(blank=True, null=True)),
                ('drzanie', models.CharField(blank=True, null=True)),
                ('vyska', models.CharField(blank=True, null=True)),
                ('vaha', models.CharField(blank=True, null=True)),
                ('datum_nar', models.CharField(blank=True, null=True)),
                ('mesto_nar', models.CharField(blank=True, null=True)),
                ('krajina_nar', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sezona', models.CharField(blank=True, null=True)),
                ('klub', models.TextField(blank=True, null=True)),
                ('id_player', models.BigIntegerField(blank=True, null=True)),
                ('hlava', models.TextField(blank=True, null=True)),
                ('meno', models.TextField(blank=True, null=True)),
                ('pozicia', models.TextField(blank=True, null=True)),
                ('zapasy', models.BigIntegerField(blank=True, null=True)),
                ('g', models.BigIntegerField(blank=True, db_column='g', null=True)),
                ('a', models.BigIntegerField(blank=True, db_column='a', null=True)),
                ('b', models.BigIntegerField(blank=True, db_column='b', null=True)),
                ('plusminus', models.BigIntegerField(blank=True, db_column='plusminus', null=True)),
                ('v', models.BigIntegerField(blank=True, db_column='v', null=True)),
                ('gvp', models.BigIntegerField(blank=True, db_column='gvp', null=True)),
                ('gvo', models.BigIntegerField(blank=True, db_column='gvo', null=True)),
                ('v_g', models.BigIntegerField(blank=True, db_column='v_g', null=True)),
                ('gvot', models.BigIntegerField(blank=True, db_column='gvot', null=True)),
                ('strely', models.BigIntegerField(blank=True, null=True)),
                ('perc_strel', models.FloatField(blank=True, null=True)),
                ('buly', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stats',
                'managed': False,
            },
        ),
    ]
